config/routes.rb
Rails.application.routes.draw do

  resources :lists
  resources :tags
  root 'static_pages#home'

  resources :boards
  resources :users

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'boards/:id/unassign/:member_id' => 'boards#unassign'
  get 'boards/:id/assign_members' => 'boards#assign_members'
  patch 'boards/:id/member_assignment' => 'boards#member_assignment'

end

app/models/user.rb
class User < ActiveRecord::Base

  serialize :boards, Array

  before_save { self.email = email.downcase }

  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 60 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user

  def show
    @boards = Board.all
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash.now[:success] = "Bem Vindo!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:success] = "Quadro atualizado com sucesso!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role, :member_boards)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_boards.html.erb
<div id="user-boards">
    <% @admin_boards.each do |b| %>
      <% board = Board.find(b) %>
      <%= link_to board.name, board_path(board), class: 'btn btn-primary', id: 'board-btn' %></li>
    <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editar usuário</h1>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |error_message| %>
    <%= error_message %>
  <% end %>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name, "Nome" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "Email" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "Senha" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmar senha" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Salvar", class: 'form-control btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Usuários</h1>

<% @users.each do |user| %>
  <div class="all-users">
    <ul>
      <li><%= link_to user.name, user_path(user) %></li>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Cadastre-se</h1>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |error_message| %>
    <%= error_message %>
  <% end %>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name, "Nome" %>
      <%= f.text_field :name, class: 'form-control', placeholder: "Digite aqui seu nome" %>

      <%= f.label :email, "Email" %>
      <%= f.email_field :email, class: 'form-control', placeholder: "exemplo@exemplo.com" %>

      <%= f.label :password, "Senha" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmar senha" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Criar conta", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>

<div class="btn-group" id="profile-conf">
    <%= link_to "Editar perfil", edit_user_path, class: "btn btn-default" %>
    <!-- <%= link_to "Excluir perfil", user_path, method: :delete, class: "btn btn-default", data: { confirm: "Você tem certeza que deseja excluir sua conta?" } %> -->
</div>

<table class='table' id="profile-table">
  <tr>
    <td class="align-center">Nome</td>
    <td class="align-center"><%= @user.name %></td>
  </tr>
  <tr>
    <td class="align-center">Email</td>
    <td class="align-center"><%= @user.email %></td>
  </tr>
</table>