config/routes.rb
Rails.application.routes.draw do

  resources :lists
  resources :tags
  root 'static_pages#home'

  resources :boards
  resources :users

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'boards/:id/unassign/:member_id' => 'boards#unassign'
  get 'boards/:id/assign_members' => 'boards#assign_members'
  patch 'boards/:id/member_assignment' => 'boards#member_assignment'

end

app/models/board.rb
class Board < ActiveRecord::Base

  serialize :members, Array
  serialize :admin, Array
  serialize :tags, Array

  validates_presence_of :description, :name

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  before_action :authenticate_user

  def new
    @board = Board.new
    @users = User.all - [current_user]
    @tags = Tag.all
  end

  def create
    @board = Board.new(board_params)
   
    members = params[:board][:members].reject{ |u| u == "0" } unless params[:board][:members].nil?
    @board.members = members unless members.nil?
    @board.admin.push(current_user.id)

    tags = params[:board][:tags].reject{ |u| u == "0" } unless params[:board][:tags].nil?
    @board.tags = tags unless tags.nil?

    if @board.save
      flash[:success] = "Quadro criado com sucesso!"
      redirect_to @board
    else
      render 'new'
    end
  end

  def show
    @board = Board.find(params[:id])
  end

  def index
    @boards = Board.all
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])

    if @board.update_attributes(board_params)
      flash[:success] = "Quadro atualizado com sucesso!"
      redirect_to @board
    else
      render 'edit'
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    
    redirect_to root_path          
  end

  def assign_members
    @board = Board.find(params[:id])
    members = @board.members

    ids = []
    User.all.each do |id|
      ids.push(id)
    end

    @users = ids - [members] - [current_user.id]
  end

  def member_assignment
    @board = Board.find(params[:id])

    members = params[:board][:members].reject{ |u| u == "0" } unless params[:board][:members].nil?
    @board.members =members unless members.nil?

    @board.save

    redirect_to @board
  end

  def unassign
    @board = Board.find(params[:id])
    @board.members.delete(params[:member_id])
    @board.save
    redirect_to @board
  end

  private

    def board_params
      params.require(:board).permit(:description, :name, :admin)
    end
end

app/helpers/board_helper.rb
module BoardHelper
end

app/views/boards/_all_boards.html.erb
<div id="all-boards">
    <% @boards.each do |board| %>
        <%= link_to board.name, board_path(board), class: 'btn btn-primary', id: 'board-btn' %></li>
    <% end %>
</div>

app/views/boards/assign_members.html.erb
<%= form_for @board, :url => "member_assignment" do |f| %>

  <h2>Vincular membros</h2>

  <div id="member-selection">
    <% @users.each do |id| %>
      <div id="select-members">
        <%= f.check_box(:members, { :multiple => true }, id) %>
        <% u = User.find(id) %>
        <%= u.name %>
      </div>
    <% end %>
  </div>

  <%= f.submit "Criar quadro", class: 'form-control btn btn-primary' %>

<% end %>

app/views/boards/edit.html.erb
<h1>Editar <%= @board.name %></h1>

<% if @board.errors.any? %>
    <% @board.errors.full_messages.each do |error_message| %>
    <%= error_message %>
  <% end %>
<% end %>

<%= form_for @board do |f| %>
 
  <div class='new-board-info'>
    <div id='board-name-field'>
      <%= f.label :name, "Nome" %>
      <%= f.text_field :name %>
    </div>

    <div id='board-description-field'>
      <%= f.label :description, "Descrição" %>
      <%= f.text_area :description %>
    </div>
  </div>

  <%= f.submit "Atualizar quadro" %>

<% end %>

app/views/boards/index.html.erb
<h1>Quadros</h1>

<%= render :partial => 'all_boards' %>

<%= link_to "Criar novo quadro", new_board_path %>

app/views/boards/member_assignment.html.erb
<h1>Vincular membros em <%= @board.name %></h1>

<%= form_for @board do |f| %>
  <div id="member-selection">
    <% @users.each do |user| %>
      <div id="select-members">
        <%= f.check_box(:members, { :multiple => true }, user.id) %>
        <%= user.name %>
      </div>
    <% end %>
  </div>

  <%= f.submit "Vincular  ", class: 'form-control btn btn-primary' %>

<% end %>

app/views/boards/new.html.erb
<h1> Crie um novo quadro </h1>

<% if @board.errors.any? %>
    <% @board.errors.full_messages.each do |error_message| %>
    <%= error_message %>
  <% end %>
<% end %>

<%= form_for @board do |f| %>

  <div class='new-board-info'>
    <div id='board-name-field'>
      <%= f.label :name, "Nome" %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div id='board-description-field'>
      <%= f.label :description, "Descrição" %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div id="selection">
    <div id="member-sel-title"><h2>Vincular membros</h2></div>
    <div id="tag-sel-title"><h2>Adicionar etiquetas ao quadro</h2></div>

    <div id="member-selection">
      <% @users.each do |user| %>
        <div id="select-members">
          <%= f.check_box(:members, { :multiple => true }, user.id) %>
          <%= user.name %>
        </div>
      <% end %>
    </div>

    <div id="tag-selection">
      <% @tags.each do |tag| %>
        <div id="select-tags">
          <%= f.check_box(:tags, { :multiple => true }, tag.id) %>
          <%= tag.name %>
        </div>
      <% end %>
    </div>
  </div>

  <%= f.submit "Criar quadro", class: 'form-control btn btn-primary' %>

<% end %>

app/views/boards/show.html.erb
<h1> <%= @board.name %> </h1>

<div class="btn-group" id="profile-conf">
<%= link_to "Adicionar membros", "", class: "btn btn-default" %>
<%= link_to "Editar quadro", edit_board_path, class: "btn btn-default" %>
<%= link_to "Excluir quadro", board_path, method: :delete, class: "btn btn-default", data: { confirm: "Você tem certeza que deseja excluir este quadro?" } %>
</div>

<h2>Informações do quadro</h2>

<table class='table' id="board-info">
  <tr>
    <td class="align-center">Nome</td>
    <td class="align-center"><%= @board.name %></td>
  </tr>
  <tr>
    <td class="align-center">Descrição</td>
    <td class="align-center"><%= @board.description %></td>
  </tr>
</table>


<h2>Membros</h2>

<% @board.members.each do |m| %>
    <% b = User.find(m) %>
    <div class="btn-group">
      <%= link_to b.name, user_path(b), class: "btn btn-success" %>
      <%= link_to "-", "#{@board.id}/unassign/#{b.id}", class: "btn btn-danger", id: "unassign-member" %>
    </div>
<% end %>

<h2>Etiquetas</h2>

<% @board.tags.each do |m| %>
    <% b = Tag.find(m) %>
    <div class="btn-group">
      <%= link_to b.name, tag_path(b), class: "btn btn-success" %>
    </div>
<% end %>